Basicuser:
    type: entity
    table: basicuser
    indexes:
        FKBasicUser688948:
            columns:
                - user
    id: {  }
    fields:
        firstname:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: firstName
        lastname:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: lastName
        age:
            type: integer
            nullable: false
            options:
                unsigned: false
        sex:
            type: boolean
            nullable: false
    oneToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user:
                    referencedColumnName: user
            orphanRemoval: false
    lifecycleCallbacks: {  }
