Business:
    type: entity
    table: business
    indexes:
        FKBusiness343247:
            columns:
                - user
        FKBusiness476311:
            columns:
                - idCategory
    id: {  }
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        address:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        phone1:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        phone2:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
        phone3:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
        presentation:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        trial:
            type: boolean
            nullable: false
    manyToOne:
        idcategory:
            targetEntity: Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idCategory:
                    referencedColumnName: idCategory
            orphanRemoval: false
    oneToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user:
                    referencedColumnName: user
            orphanRemoval: false
    lifecycleCallbacks: {  }
