Productsandservices:
    type: entity
    table: productsandservices
    indexes:
        FKProductsAn148047:
            columns:
                - user
    id:
        idpproductsandservices:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idPproductsandservices
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        user:
            targetEntity: Business
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user:
                    referencedColumnName: user
            orphanRemoval: false
    lifecycleCallbacks: {  }
