User:
    type: entity
    table: user
    uniqueConstraints:
        email:
            columns:
                - email
    id:
        user:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            id: true
            generator:
                strategy: NONE
    fields:
        password:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        country:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        city:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        website:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        language:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        registrationdate:
            type: date
            nullable: false
            column: registrationDate
        active:
            type: boolean
            nullable: false
        salt:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        lastaccess:
            type: date
            nullable: false
            column: lastAccess
        perfilphoto:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: perfilPhoto
    lifecycleCallbacks: {  }
