# app/config/security.yml
security:
    encoders:
        Hub\HubBundle\Entity\User: plaintext
            #algorithm: sha1
            #encode_as_base64: false
            #iterations: 1
    #role_hierarchy:
       # ROLE_ADMIN: ROLE_USER
       # ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
    providers:
        administrators:
            entity: { class: HubBundle:User, property: user }
    firewalls:
        admin_area:
            pattern: ^/  
            provider: administrators
            #http_basic: ~
            form_login:
                check_path: /login_check
                login_path: /login
            anonymous: ~
            logout: 
                path: /logout
                target: /
    access_control:
        #- { path: ^/test, roles: ROLE_USER, requires_channel: https }
        - { path: ^/admin, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/professional, roles: ROLE_PROFESSIONAL, requires_channel: https }